### ISSUE TITLE
Breaks bbPress profile editing

### ISSUE THREAD

**Issue by kasparsd** [WordPress/two-factor#175]
See https://wordpress.org/support/topic/plugin-breaks-bbpress-profile-editing/

> When you click on someone’s username in a bbPress forum, it brings up information from your WordPress profile and integrates it into your site’s theme. If you’re viewing your own profile, you can also edit it from there, without ever going into wp-admin:
> 
> When enabling Two Factor, however, it completely breaks the page, and produces this error at the bottom of a stream of unformatted text:

```
Fatal error: Uncaught Error: Call to undefined function convert_to_screen() in /home/public/wp-admin/includes/class-wp-list-table.php:143 Stack trace: 
#0 /home/public/wp-content/plugins/two-factor/providers/class.two-factor-fido-u2f-admin.php(189): WP_List_Table->__construct() 
#1 /home/public/wp-includes/class-wp-hook.php(298): Two_Factor_FIDO_U2F_Admin::show_user_profile(Object(WP_User)) 
#2 /home/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) 
#3 /home/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#4 /home/public/wp-content/plugins/two-factor/class.two-factor-core.php(636): do_action('show_user_secur...', Object(WP_User)) 
#5 /home/public/wp-includes/class-wp-hook.php(298): Two_Factor_Core::user_two_factor_options(Object(WP_User)) 
#6 /home/public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) 
#7 /home/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) 
#8 /home/public/wp-content/plugins/bbpress/includes/users/functions.php(1662): do_action('show in /home/public/wp-admin/includes/class-wp-list-table.php on line 143
```

**Comment by jeffpaul** [comment]
@CryoutCreations has a fix for this in #414.

**Comment by iandunn** [comment]
U2F is deprecated and no longer works in Chrome, so the provider is being removed in #439 . Given that, there's probably no reason to keep this open anymore.

**Comment by iandunn** [comment]
Er, actually, looking at the PR, it isn't specific to U2F, so I'll reopen.
