### ISSUE TITLE
array_filter for two_factor_providers

### ISSUE THREAD

**Issue by Whoweez** [WordPress/two-factor#326]
Good day,
Thanks for your amazing plugin.
I'm looking to extend your plugin by adding my own 2FA class.

This is what I've done:
custom plugin with code:
```
function add_two_factor( $providers ) {
    // Maybe modify $providers
   $providers['two-factor-sms'] = TWO_FACTOR_DIR.'class.two-factor-sms.php';

    return $providers;
}
add_filter( 'two_factor_providers', 'add_two_factor' );
```

in class.two-factor-sms.php I've literally duplicated the email class and changed the class name to: class Two_Factor_SMS extends Two_Factor_Provider { ...

getting error in wp-admin/profile.php:
`Fatal error: Uncaught Error: Call to a member function print_label() on string in /wp-content/plugins/two-factor/class-two-factor-core.php:757 Stack trace: #0 /wp-includes/class-wp-hook.php(288): Two_Factor_Core::user_two_factor_options(Object(WP_User)) #1 /wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array) #2 /wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /wp-admin/user-edit.php(717): do_action('show_user_profi...', Object(WP_User)) #4 /wp-admin/profile.php(18): require_once('/Users/...') #5 /Users/.composer/vendor/laravel/valet/server.php(158): require('/Users/...') #6 {main} thrown in /wp-content/plugins/two-factor/class-two-factor-core.php on line 757`

Not too sure what is the problem here...?

Would appreciate any assistance :)

Kind regards,
Wzz

**Comment by Whoweez** [comment]
No worries, my class name was provided wrong :) Thanks for the amazing plugin!
